/*
  AUTOR: RenzoZ
  OBJETIVO: CREAR SECUENCIALES PARA CADA TABLA QUE ES NECESARIA
*/



-- CREACION DEL SECUENCIAL SEQ_METODO_DETECCION PARA LA TABLA METODO_DETECCION

CREATE SEQUENCE SEQ_METODO_DETECCION
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_CASOS_POSITIVOS PARA LA TABLA CASOS_POSITIVOS

CREATE SEQUENCE SEQ_CASOS_POSITIVOS
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_GRUPO_RIESGO PARA LA TABLA GRUPO_RIESGO

CREATE SEQUENCE SEQ_GRUPO_RIESGO
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_DIRESA PARA LA TABLA DIRESA

CREATE SEQUENCE SEQ_DIRESA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_REGISTRO_VACUNACION PARA LA TABLA REGISTRO_VACUNACION

CREATE SEQUENCE SEQ_REGISTRO_VACUNACION
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_AUDITORIA_DIRESA PARA LA TABLA AUDITORIA_DIRESA

CREATE SEQUENCE SEQ_AUDITORIA_DIRESA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_AUDITORIA_FABRICANTE PARA LA TABLA AUDITORIA_FABRICANTE

CREATE SEQUENCE SEQ_AUDITORIA_FABRICANTE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_AUDITORIA_GRUPO_RIESGO PARA LA TABLA AUDITORIA_GRUPO_RIESGO

CREATE SEQUENCE SEQ_AUDITORIA_GRUPO_RIESGO
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_AUDITORIA_METODO PARA LA TABLA AUDITORIA_METODO_DETECCION

CREATE SEQUENCE SEQ_AUDITORIA_METODO
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_AUDITORIA_PERSONA PARA LA TABLA AUDITORIA_PERSONA

CREATE SEQUENCE SEQ_AUDITORIA_PERSONA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_AUDITORIA_POSITIVOS PARA LA TABLA AUDITORIA_CASOS_POSITIVOS

CREATE SEQUENCE SEQ_AUDITORIA_POSITIVOS
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


-- CREACION DEL SECUENCIAL SEQ_AUDITORIA_VACUNACION PARA LA TABLA AUDITORIA_REGISTRO_VACUNACION

CREATE SEQUENCE SEQ_AUDITORIA_VACUNACION
START WITH 1
INCREMENT BY 1
NOMAXVALUE;
