/*
  AUTOR: RenzoZ
  OBJETIVO: CREAR QUERIES QUE PERMITAN EL FILTRO DE DATOS LIMPIOS PARA SU POSTERIOR INSERCCION A LAS TABLAS CREADAS A PARTIR DEL MODELO RELACIONAL
*/



--ELIMINACION DE DATOS DUPLICADOS EN LA TABLA DICC_DEPARTAMENTO PARA SU POSTERIOR INSERCION A LA TABLA DEPARTAMENTO

DELETE FROM DICC_DEPARTAMENTO
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM DICC_DEPARTAMENTO
    GROUP BY COD_DEPARTAMENTO
);

--INSERCCION DE LOS DATOS LIMPIOS A LA TABLA DEPARTAMENTO

INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO, NOM_DEPARTAMENTO)
SELECT COD_DEPARTAMENTO, NOM_DEPARTAMENTO
FROM DICC_DEPARTAMENTO
ORDER BY 1 ASC;




--ELIMINACION DE DATOS DUPLICADOS EN LA TABLA DICC_PROVINCIA PARA SU POSTERIOR INSERCION A LA TABLA PROVINCIA

DELETE FROM DICC_PROVINCIA
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM DICC_PROVINCIA
    GROUP BY COD_PROVINCIA
);

--INSERCCION DE LOS DATOS LIMPIOS A LA TABLA PROVINCIA

INSERT INTO PROVINCIA(COD_PROVINCIA, NOM_PROVINCIA, COD_DEPARTAMENTO)
SELECT COD_PROVINCIA, NOM_PROVINCIA, COD_DEPARTAMENTO
FROM DICC_PROVINCIA
ORDER BY 1 ASC;




--INSERCCION DE LOS DATOS LIMPIOS A LA TABLA DISTRITO

INSERT INTO DISTRITO(COD_UBIGEO, NOM_DISTRITO, COD_PROVINCIA)
SELECT COD_UBIGEO, NOM_DISTRITO, COD_PROVINCIA
FROM DICC_DISTRITO
ORDER BY 1 ASC;




--INSERCION DE LOS DATOS A LA TABLA METODO_DETECCION

INSERT INTO METODO_DETECCION(COD_METODO, NOM_METODO)
VALUES(SEQ_METODO_DETECCION.NEXTVAL, 'AG');

INSERT INTO METODO_DETECCION(COD_METODO, NOM_METODO)
VALUES(SEQ_METODO_DETECCION.NEXTVAL, 'PR');

INSERT INTO METODO_DETECCION(COD_METODO, NOM_METODO)
VALUES(SEQ_METODO_DETECCION.NEXTVAL, 'PCR');




--INSERCCION DE LOS DATOS LIMPIOS Y UNICOS A LA TABLA PERSONA

INSERT INTO PERSONA(COD_UUID, SEXO, EDAD, COD_UBIGEO)
SELECT 
    MAX(IDT) AS IDT, 
    MAX(SEXO) AS SEXO, 
    MAX(EDAD) AS EDAD, 
    MAX(UBIGEO) AS UBIGEO
FROM (
    SELECT ID_PERSONA AS IDT, SEXO, EDAD, UBIGEO FROM DICC_CASOS
    UNION
    SELECT UUII AS IDT, SEXO, EDAD, NULL AS UBIGEO FROM DICC_VACUNAS
) t
GROUP BY IDT
HAVING MAX(IDT) IS NOT NULL;




--INSERCCION DE LOS DATOS LIMPIOS A LA TABLA CASOS_POSITIVOS

INSERT INTO CASOS_POSITIVOS(COD_CASO, COD_UUID, COD_METODO, FECHA_RESULTADO)
SELECT SEQ_CASOS_POSITIVOS.NEXTVAL, ID_PERSONA, (SELECT COD_METODO FROM METODO_DETECCION WHERE NOM_METODO = METODODX), FECHA_RESULTADO 
FROM DICC_CASOS
WHERE ID_PERSONA IS NOT NULL;




--INSERCION DE LOS DATOS LIMPIOS Y UNICOS A LA TABLA GRUPO_RIESGO

INSERT INTO GRUPO_RIESGO(COD_GRUPO, TIPO_GRUPO)
SELECT SEQ_GRUPO_RIESGO.NEXTVAL, GRUPO_RIESGO
FROM (SELECT DISTINCT GRUPO_RIESGO FROM DICC_VACUNAS);




--INSERCION DE LOS DATOS A LA TABLA FABRICANTE

INSERT INTO FABRICANTE(COD_FABRICANTE,NOM_FABRICANTE)
VALUES(1,'JANSSEN');

INSERT INTO FABRICANTE(COD_FABRICANTE,NOM_FABRICANTE)
VALUES(2,'SINOPHARM');

INSERT INTO FABRICANTE(COD_FABRICANTE,NOM_FABRICANTE)
VALUES(3,'PFIZER');

INSERT INTO FABRICANTE(COD_FABRICANTE,NOM_FABRICANTE)
VALUES(4,'ASTRAZENECA');

INSERT INTO FABRICANTE(COD_FABRICANTE,NOM_FABRICANTE)
VALUES(5,'MODERNA');




--INSERCION DE LOS DATOS LIMPIOS Y UNICOS A LA TABLA DIRESA

INSERT INTO DIRESA(COD_DIRESA, CENTRO_DIRESA)
SELECT SEQ_DIRESA.NEXTVAL, DIRESA
FROM (SELECT DISTINCT DIRESA FROM DICC_VACUNAS);




--INSERCION DE LOS DATOS LIMPIOS A LA TABLA REGISTRO_VACUNACION

INSERT INTO REGISTRO_VACUNACION(COD_VACUNACION, COD_UUID, COD_DIRESA, COD_UBIGEO, COD_GRUPO, COD_FABRICANTE, NUM_DOSIS, FECHA_VACUNACION, CLASIFICACION_VACUNA, TIPO_EDAD)
SELECT
        SEQ_REGISTRO_VACUNACION.NEXTVAL, --CAMPO COD_VACUNACION
        dv.UUII, --CAMPO COD_UUID
        (SELECT COD_DIRESA FROM DIRESA WHERE CENTRO_DIRESA = dv.DIRESA) AS COD_DIRESA, --COLUMN COD_DIRESA
        (
            SELECT d.COD_UBIGEO 
            FROM DISTRITO d 
            JOIN PROVINCIA p ON p.COD_PROVINCIA = d.COD_PROVINCIA
            JOIN DEPARTAMENTO x ON x.COD_DEPARTAMENTO = p.COD_DEPARTAMENTO
            WHERE d.NOM_DISTRITO = dv.DISTRITO AND p.NOM_PROVINCIA = dv.PROVINCIA AND x.NOM_DEPARTAMENTO = dv.DEPARTAMENTO
        ) AS COD_UBIGEO,--COLUMN COD_UBIGEO
        (SELECT COD_GRUPO FROM GRUPO_RIESGO WHERE TIPO_GRUPO = dv.GRUPO_RIESGO) AS COD_GRUPO, --CAMPO COD_GRUPO
        (SELECT COD_FABRICANTE FROM FABRICANTE WHERE NOM_FABRICANTE = dv.FABRICANTE) AS COD_FABRICANTE, --CAMPO COD_FABRICANTE
        dv.DOSIS, --CAMPO NUM_DOSIS
        dv.FECHA_VACUNACION, --CAMPO FECHA_VACUNACION
        dv.CLASIFICACION_VACUNA, --CAMPO CLASIFICACION_VACUNA
        dv.TIPO_EDAD --CAMPO TIPO_EDAD;
FROM DICC_VACUNAS dv
WHERE dv.UUII IS NOT NULL;
