/*
  AUTOR: RenzoZ
  OBJETIVO: CREAR TABLAS QUE SIRVAN COMO AUDITORIA Y REGISTREN CUALQUIER TRANSACCION EN ELLAS
*/


-- CREACION DE LA TABLA AUDITORIA_DIRESA Y SUS CONSTRAINTS
CREATE TABLE AUDITORIA_DIRESA
(
COD_AUDI_DIRESA NUMBER,
ACCION VARCHAR2(20),
USUARIO VARCHAR2(20),
FECHA TIMESTAMP
)TABLESPACE TBS_D;

ALTER TABLE AUDITORIA_DIRESA
ADD CONSTRAINT PK_COD_AUDI_DIRESA
PRIMARY KEY (COD_AUDI_DIRESA);



-- CREACION DE LA TABLA AUDITORIA_FABRICANTE Y SUS CONSTRAINTS

CREATE TABLE AUDITORIA_FABRICANTE
(
COD_AUDI_FABRICANTE NUMBER,
ACCION VARCHAR2(20),
USUARIO VARCHAR2(20),
FECHA TIMESTAMP
)TABLESPACE TBS_D;


ALTER TABLE AUDITORIA_FABRICANTE
ADD CONSTRAINT PK_COD_AUDI_FABRICANTE
PRIMARY KEY(COD_AUDI_FABRICANTE);



-- CREACION DE LA TABLA AUDITORIA_GRUPO_RIESGO Y SUS CONSTRAINTS

CREATE TABLE AUDITORIA_GRUPO_RIESGO
(
COD_AUDI_GRUPO NUMBER,
ACCION VARCHAR2(20),
USUARIO VARCHAR2(20),
FECHA TIMESTAMP
)TABLESPACE TBS_D;


ALTER TABLE AUDITORIA_GRUPO_RIESGO
ADD CONSTRAINT PK_COD_AUDI_GRUPO
PRIMARY KEY(COD_AUDI_GRUPO);



-- CREACION DE LA TABLA AUDITORIA_METODO_DETECCION Y SUS CONSTRAINTS

CREATE TABLE AUDITORIA_METODO_DETECCION
(
COD_AUDI_METODO NUMBER,
ACCION VARCHAR2(20),
USUARIO VARCHAR2(20),
FECHA TIMESTAMP
)TABLESPACE TBS_D;


ALTER TABLE AUDITORIA_METODO_DETECCION
ADD CONSTRAINT PK_COD_AUDI_METODO
PRIMARY KEY(COD_AUDI_METODO);



-- CREACION DE LA TABLA AUDITORIA_PERSONA Y SUS CONSTRAINTS

CREATE TABLE AUDITORIA_PERSONA
(
COD_AUDI_PERSONA NUMBER,
ACCION VARCHAR2(20),
USUARIO VARCHAR2(20),
FECHA TIMESTAMP
)TABLESPACE TBS_D;


ALTER TABLE AUDITORIA_PERSONA
ADD CONSTRAINT PK_COD_AUDI_PERSONA
PRIMARY KEY(COD_AUDI_PERSONA);



-- CREACION DE LA TABLA AUDITORIA_CASOS_POSITIVOS Y SUS CONSTRAINTS

CREATE TABLE AUDITORIA_CASOS_POSITIVOS
(
COD_AUDI_POSITIVOS NUMBER,
ACCION VARCHAR2(20),
USUARIO VARCHAR2(20),
FECHA TIMESTAMP
)TABLESPACE TBS_D;


ALTER TABLE AUDITORIA_CASOS_POSITIVOS
ADD CONSTRAINT PK_COD_AUDI_POSITIVOS
PRIMARY KEY(COD_AUDI_POSITIVOS);



-- CREACION DE LA TABLA AUDITORIA_REGISTRO_VACUNACION Y SUS CONSTRAINTS

CREATE TABLE AUDITORIA_REGISTRO_VACUNACION
(
COD_AUDI_VACUNACION NUMBER,
ACCION VARCHAR2(20),
USUARIO VARCHAR2(20),
FECHA TIMESTAMP
)TABLESPACE TBS_D;


ALTER TABLE AUDITORIA_REGISTRO_VACUNACION
ADD CONSTRAINT PK_COD_AUDI_VACUNACION
PRIMARY KEY(COD_AUDI_VACUNACION);
